language: rust

sudo: required

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - llvm-3.8
      - llvm-3.8-dev
      - clang-3.8
      - libedit-dev
rust:
  - 1.16.0

script:
  - llvm-config --version
  - cargo build --verbose
  - cargo test --verbose
