language: rust

dist: trusty
sudo: required

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - llvm-3.9
      - llvm-3.9-dev
      - clang-3.9
      - libedit-dev
rust:
  - 1.19.0

script:
  - which llvm-config
  - sudo ln -sf /usr/bin/llvm-config-3.9 /usr/local/clang-5.0.0/bin/llvm-config
  - llvm-config --version
  - cargo build --verbose
  - cargo test --verbose
