version: 2

jobs:
  build:
    docker:
      # - image: ubuntu:16.04
      - image: uint256/rucc:latest

    working_directory: /opt/rucc

    steps:
      - checkout
      - run:
          name: Test and Coverage
          command: |
            export PATH=~/.cargo/bin:$PATH
            RUST_TEST_THREADS=1
            RUSTFLAGS='-C link-args=-lffi' cargo tarpaulin --verbose --out Xml
            bash <(curl -s https://codecov.io/bash)
