version: 2

jobs:
  build:
    working_directory: /opt/rucc

    docker:
      - image: uint256/rucc:latest

    steps:
      - run:
          command: echo "[build]" > ~/.cargo/config
          command: echo "rustflags = [\"-C]\", \"link-args=-lffi\"]" >> ~/.cargo/config
          command: cargo test
