version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04

    working_directory: /opt/rucc

    steps:
      - checkout
      - run:
          command: set -eux
      - run:
          command: apt-get update
      - run:
          command: apt-get install -y zlib1g-dev wget
      - run:
          command: |
            wget "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
            chmod +x rustup-init
            ./rustup-init -y --no-modify-path --default-toolchain nightly
            RUSTUP_HOME=~/.cargo/bin/rustup
            CARGO_HOME=~/.cargo/bin/cargo
            chmod -R a+w $RUSTUP_HOME $CARGO_HOME;
            rm rustup-init
            source ~/.cargo/env
      - run:
          command: apt-get install clang-4.0 llvm-4.0 llvm-4.0-dev opt libedit-dev build-essential make -y; 
      - run: 
          command: |
            ln -s /usr/bin/clang-4.0 /usr/bin/clang; 
            ln -s /usr/bin/clang++-4.0 /usr/bin/clang++; 
            ln -s /usr/bin/llvm-config-4.0 /usr/bin/llvm-config;
      - run:
          command: |
            export PATH=~/.cargo/bin:$PATH
            cargo test
