version: 2

jobs:
  build:
    working_directory: /opt/rucc

    docker:
      - image: uint256/rucc:latest

    steps:
      - checkout
      - run:
          command: RUSTFLAGS="-C link-args=-lffi" cargo test
